seed: 5
raw_data_dir: "/home/cxu/new_data/exp2/reindex_bags/data"
out_dir: "" # specify output dir. Leave empty to use the viewport dir
replicate: True # whether to copy the used data from the original folder to the non-noisy folder
imu: {
    # from https://github.com/ethz-asl/rotors_simulator/blob/7f6b5529bfc793e77275ca32d8e4970a0c755e5d/rotors_gazebo/models/rotors_description/urdf/iris_base.xacro#L52
    "enable": True, # if add noise
    "noise_model": "gaussian", # or groundtruth
    "config":
      {
        "frequency": 240.0,
        "gyro_bias_corr_time": 1000.0,
        "gyro_noise_density": 0.0003394,
        "gyro_random_walk": 0.000038785,
        "accel_bias_corr_time": 300,
        "accel_noise_density": 0.004,
        "accel_random_walk": 0.006,
        "gyro_turn_bias": 0.0087,
        "accel_turn_bias": 0.1960,
      },
    "folder": # Define the data to be processed in "raw_data_dir"
    [
      "imu_camera",
      "imu_body"
    ],
  }
camera: {
    "enable": True,
    "output_depth_img": True, # transfer the depth npy file to png image
    "noise_model": "realsense", # kinect (not complete -- need to mask the rgb), gaussian, groundtruth
    "config":
      {
        "depth_factor": 1000.0,
        "minimum_depth": 0.01,
        "maximum_depth": 3.5,
        "subpixel": 0.2,
        "maximum_depth_variance": 10.0,
        "flatten_distance": 0,
        "camera_params": [1920, 1080, 977.7309, 898.4482, 960, 540],
        "hfov": 88.95,
      },
  }
blur:
  {
    "enable": True,
    "imu_dir_for_blurry": "imu_camera", # raw_data_dir + this_imu_dir
    "odom_dir_for_blurry": "odom", # raw_data_dir + this_odom_dir
    "config":
      {
        "num_imu_sample": 10,
        "exposure_time": [0, 0.1],
        "num_pose": 30,
        "readout_mean": 0.015,
        "readout_std": 0.006,
      },
  }
